name: getBranchName
on: [pull_request]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    steps:

      # extract branch name on pull request
      - name: Print branch name
        id: imprimir
        if: github.event_name == 'pull_request'
        run: echo "::set-output name=respuesta::${GITHUB_HEAD_REF}"

      # print branch name
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME   
  Mi-segundo-job:
    needs: which_branch
    name: Mi segundo job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir
      id: imprimir
      run: echo ${{needs.which_branch.outputs.salida}}